<?php
return [
    'login_title' => 'Anmeldung',
    'email' => 'E-Mail',
    'password' => 'Passwort',
    'remember' => 'Angemeldet bleiben',
    'change_password' => 'Passwort ändern',
    'logout' => 'Abmelden',
    'dashboard' => 'Dashboard',
    'persons' => 'Personen',
    'horses' => 'Pferde',
    'clubs' => 'Vereine',
    'events' => 'Turniere',
    'classes' => 'Prüfungen',
    'entries' => 'Nennungen',
    'startlist' => 'Startlisten',
    'schedule' => 'Zeitplan',
    'display' => 'Anzeige',
    'judge' => 'Richten',
    'results' => 'Ergebnisse',
    'helpers' => 'Helfer',
    'print' => 'Druck',
    'export' => 'Export',
];
